fragment UserBookFragment on user_books {
    id
    status_id
    edition_id
    last_read_date
    date_added
    privacy_setting_id
    rating
    referrer_user_id
    review_has_spoilers
    reviewed_at
    updated_at
    created_at

    progress_updated_journal: reading_journals(
        where: { event: { _eq: "progress_updated" } }
        order_by: { updated_at: desc }
        limit: 1
    ) {
        ...ReadingJournalFragment
    }

    status_currently_reading_journal: reading_journals(
        where: { event: { _eq: "status_currently_reading" } }
        order_by: { updated_at: desc }
        limit: 1
    ) {
        ...ReadingJournalFragment
    }

    user_book_read_finished_journal: reading_journals(
        where: { event: { _eq: "user_book_read_finished" } }
        order_by: { updated_at: desc }
        limit: 1
    ) {
        ...ReadingJournalFragment
    }

    status_stopped_journal: reading_journals(
        where: { event: { _eq: "status_stopped" } }
        order_by: { updated_at: desc }
        limit: 1
    ) {
        ...ReadingJournalFragment
    }

    user_book_reads(
        order_by: [{ started_at: asc_nulls_first }, { id: desc }]
        limit: 1
    ) {
        ...UserBookReadFragment
    }

    book {
        ...BookListFragment
    }

    edition {
        ...EditionFragment
    }
}
